# Generated by Django 4.1 on 2022-09-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_creation',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='post_category',
        ),
    ]
