# Generated by Django 4.1 on 2022-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='CategoryPost',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dateCreation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news.CategoryPost', to='news.category'),
        ),
    ]
